name: Update Leaderboard

on:
  schedule:
    - cron: '0 */12 * * *'  # Every 12 hours
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: main

    - name: Fetch leaderboard data
      run: |
        curl -s https://play.mirageonlineclassic.com/leaderboard.json -o leaderboard_cache.json
        cat leaderboard_cache.json

    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Check for changes and commit
      run: |
        git add leaderboard_cache.json || true
        if git diff --staged --quiet; then
          echo "No changes to commit."
        else
          git commit -m "Update leaderboard data"
          git push origin main
        fi
